import type { Producer, Product, Order, Review } from "./types";

export const MOCK_PRODUCERS: Producer[] = [
  {
    id: "producer-1",
    userId: "user-1",
    name: "La Belle Pâtisserie",
    slug: "la-belle-patisserie",
    bio: "Handcrafted celebration cakes, patisserie, and baked goods made to order in our Nottingham studio kitchen. Every creation is layered, decorated, and packed by hand.",
    story:
      "I trained as a pastry chef in Lyon before moving back to Nottingham in 2016. Two years later I started taking cake orders from the kitchen table — a Victoria sponge here, a birthday tier there. Word spread faster than I ever expected. Today we have a dedicated studio on Hockley, a small team of four bakers, and a reputation for cakes that actually taste as good as they look. We only use free-range eggs, unbleached flour, and real butter. No shortening, no artificial flavourings. Everything is made fresh to order — we don't bake for stock. If you want something that people will still be talking about at the end of the party, you've come to the right place.",
    location: "Hockley, Nottingham",
    address: {
      line1: "Studio 7, Hockley Works",
      city: "Nottingham",
      county: "Nottinghamshire",
      postcode: "NG1 1FH",
      country: "GB",
    },
    categories: ["cakes", "patisserie"],
    images: {
      banner: "/images/hero.jpg",
      logo: "/images/macarons.jpg",
    },
    status: "approved",
    commissionRate: 0,
    fulfilmentOptions: ["ship", "collect"],
    socialLinks: {
      instagram: "@labellepatisserie",
      facebook: "LaBellePâtisserie",
    },
    rating: 4.9,
    reviewCount: 412,
    createdAt: new Date("2018-03-01"),
  },
];

export const MOCK_PRODUCTS: Product[] = [
  {
    id: "prod-1",
    producerId: "producer-1",
    producerName: "La Belle Pâtisserie",
    producerSlug: "la-belle-patisserie",
    name: "Classic Victoria Sponge",
    description:
      "Our signature two-tier Victoria sponge — light vanilla genoise, fresh strawberry jam, and lightly sweetened Chantilly cream. Serves 10–12. Made to order with free-range eggs and real butter. Ready for collection or delivery within 48 hours.",
    slug: "classic-victoria-sponge",
    category: "cakes",
    price: 2800,
    unit: "whole cake (10–12 slices)",
    stock: 20,
    images: [
      "https://images.unsplash.com/photo-1464349095431-e9a21285b5f3?w=800&q=80",
      "https://images.unsplash.com/photo-1486427944299-d1955d23e34d?w=800&q=80",
    ],
    dietary: ["vegetarian"],
    allergens: ["gluten", "dairy", "eggs"],
    seasonal: false,
    available: true,
    featured: true,
    createdAt: new Date("2024-01-05"),
  },
  {
    id: "prod-2",
    producerId: "producer-1",
    producerName: "La Belle Pâtisserie",
    producerSlug: "la-belle-patisserie",
    name: "Red Velvet Celebration Cake",
    description:
      "Three layers of deep red velvet sponge with cream cheese frosting and a signature dark chocolate ganache drip. Rich, dramatic, and utterly delicious. Serves 14–16. Perfect for birthdays and celebrations. Personalised message included.",
    slug: "red-velvet-celebration-cake",
    category: "cakes",
    price: 4500,
    unit: "whole cake (14–16 slices)",
    stock: 15,
    images: [
      "https://images.unsplash.com/photo-1578985545062-69928b1d9587?w=800&q=80",
    ],
    dietary: ["vegetarian"],
    allergens: ["gluten", "dairy", "eggs"],
    seasonal: false,
    available: true,
    featured: true,
    createdAt: new Date("2024-01-05"),
  },
  {
    id: "prod-3",
    producerId: "producer-1",
    producerName: "La Belle Pâtisserie",
    producerSlug: "la-belle-patisserie",
    name: "French Macarons (box of 12)",
    description:
      "A curated box of twelve French macarons in four rotating flavours — salted caramel, raspberry, pistachio, and dark chocolate. Piped and filled by hand, with aged shells for the perfect chew. Arrives in a ribbon-tied gift box.",
    slug: "french-macarons-box-12",
    category: "patisserie",
    price: 2200,
    unit: "box of 12",
    stock: 30,
    images: [
      "https://images.unsplash.com/photo-1558326567-98ae2405596b?w=800&q=80",
    ],
    dietary: ["gluten-free", "vegetarian"],
    allergens: ["dairy", "eggs", "nuts"],
    seasonal: false,
    available: true,
    featured: true,
    createdAt: new Date("2024-02-01"),
  },
  {
    id: "prod-4",
    producerId: "producer-1",
    producerName: "La Belle Pâtisserie",
    producerSlug: "la-belle-patisserie",
    name: "Afternoon Tea Box for Two",
    description:
      "A full afternoon tea for two, freshly prepared and beautifully boxed. Includes four finger sandwiches, two scones with clotted cream and jam, four petit fours, and a selection of four mini patisseries. A perfect treat or gift.",
    slug: "afternoon-tea-box-for-two",
    category: "patisserie",
    price: 3200,
    unit: "box for 2 people",
    stock: 25,
    images: [
      "https://images.unsplash.com/photo-1579954115545-a95591f28bfc?w=800&q=80",
    ],
    dietary: ["vegetarian"],
    allergens: ["gluten", "dairy", "eggs"],
    seasonal: false,
    available: true,
    featured: true,
    createdAt: new Date("2024-01-10"),
  },
  {
    id: "prod-5",
    producerId: "producer-1",
    producerName: "La Belle Pâtisserie",
    producerSlug: "la-belle-patisserie",
    name: "Lemon Drizzle Loaf",
    description:
      "Our famous lemon drizzle — a dense, buttery loaf soaked in fresh lemon syrup and finished with a sharp lemon glaze. Keeps for four days. Made every Tuesday and Friday morning.",
    slug: "lemon-drizzle-loaf",
    category: "cakes",
    price: 1200,
    unit: "loaf (8–10 slices)",
    stock: 40,
    images: [
      "https://images.unsplash.com/photo-1586985289688-ca3cf47d3e6e?w=800&q=80",
    ],
    dietary: ["vegetarian"],
    allergens: ["gluten", "dairy", "eggs"],
    seasonal: false,
    available: true,
    featured: true,
    createdAt: new Date("2024-01-12"),
  },
  {
    id: "prod-6",
    producerId: "producer-1",
    producerName: "La Belle Pâtisserie",
    producerSlug: "la-belle-patisserie",
    name: "Vanilla Cupcakes (box of 6)",
    description:
      "Six fluffy vanilla cupcakes, each crowned with a generous swirl of Swiss meringue buttercream. Available in seasonal flavour rotations. Current rotation: classic vanilla, salted caramel, and strawberry champagne.",
    slug: "vanilla-cupcakes-box-of-6",
    category: "cakes",
    price: 1800,
    unit: "box of 6",
    stock: 35,
    images: [
      "https://images.unsplash.com/photo-1587668178277-295251f900ce?w=800&q=80",
    ],
    dietary: ["vegetarian"],
    allergens: ["gluten", "dairy", "eggs"],
    seasonal: false,
    available: true,
    createdAt: new Date("2024-01-15"),
  },
  {
    id: "prod-7",
    producerId: "producer-1",
    producerName: "La Belle Pâtisserie",
    producerSlug: "la-belle-patisserie",
    name: "Salted Caramel Choux Tower",
    description:
      "A Paris-Brest inspired choux pastry tower filled with salted caramel mousseline cream and finished with a dark caramel glaze and praline crumble. A show-stopping centrepiece for dinner parties. Serves 6–8.",
    slug: "salted-caramel-choux-tower",
    category: "patisserie",
    price: 2400,
    unit: "serves 6–8",
    stock: 10,
    images: [
      "https://images.unsplash.com/photo-1488477181946-6428a0291777?w=800&q=80",
    ],
    dietary: ["vegetarian"],
    allergens: ["gluten", "dairy", "eggs"],
    seasonal: false,
    available: true,
    createdAt: new Date("2024-03-01"),
  },
  {
    id: "prod-8",
    producerId: "producer-1",
    producerName: "La Belle Pâtisserie",
    producerSlug: "la-belle-patisserie",
    name: "Chocolate & Hazelnut Tart",
    description:
      "A crisp all-butter pastry case filled with rich dark chocolate ganache and a roasted hazelnut praline layer. Finished with tempered chocolate shards and gold leaf. Serves 8. Gluten-free pastry available on request.",
    slug: "chocolate-hazelnut-tart",
    category: "patisserie",
    price: 2600,
    unit: "whole tart (8 slices)",
    stock: 12,
    images: [
      "https://images.unsplash.com/photo-1606313564200-e75d5e30476c?w=800&q=80",
    ],
    dietary: ["vegetarian"],
    allergens: ["gluten", "dairy", "eggs", "nuts"],
    seasonal: false,
    available: true,
    createdAt: new Date("2024-02-10"),
  },
];

export const MOCK_REVIEWS: Review[] = [
  {
    id: "rev-1",
    orderId: "order-1",
    consumerId: "consumer-1",
    consumerName: "Natalie W.",
    producerId: "producer-1",
    rating: 5,
    comment:
      "Ordered the red velvet cake for my daughter's 30th and it was absolutely stunning. People were taking photos before they'd even cut it. And the taste — honestly the best cake I've ever had. Will order again and again.",
    createdAt: new Date("2024-04-12"),
  },
  {
    id: "rev-2",
    orderId: "order-2",
    consumerId: "consumer-2",
    consumerName: "Marcus T.",
    producerId: "producer-1",
    rating: 5,
    comment:
      "The afternoon tea box was phenomenal. We had it for our anniversary and it felt genuinely special — beautiful packaging, everything tasted incredible. The macarons were particularly outstanding.",
    createdAt: new Date("2024-04-20"),
  },
  {
    id: "rev-3",
    orderId: "order-3",
    consumerId: "consumer-3",
    consumerName: "Sophie H.",
    producerId: "producer-1",
    rating: 5,
    comment:
      "The lemon drizzle loaf has completely ruined supermarket cakes for me. It's dense, soaked, perfectly sharp. I now order one every week. The delivery was also super fast and beautifully wrapped.",
    createdAt: new Date("2024-05-01"),
  },
];

export const MOCK_ORDERS: Order[] = [
  {
    id: "order-demo-1",
    consumerId: "consumer-1",
    consumerName: "Demo Customer",
    items: [
      {
        productId: "prod-2",
        productName: "Red Velvet Celebration Cake",
        producerId: "producer-1",
        producerName: "La Belle Pâtisserie",
        price: 4500,
        quantity: 1,
        unit: "whole cake (14–16 slices)",
        imageUrl: "/images/hero.jpg",
      },
      {
        productId: "prod-3",
        productName: "French Macarons (box of 12)",
        producerId: "producer-1",
        producerName: "La Belle Pâtisserie",
        price: 2200,
        quantity: 1,
        unit: "box of 12",
        imageUrl: "/images/hero.jpg",
      },
    ],
    producerIds: ["producer-1"],
    status: "delivered",
    fulfilmentMethod: "delivery",
    deliveryAddress: {
      line1: "14 Castle Boulevard",
      city: "Nottingham",
      postcode: "NG7 1FB",
      country: "GB",
    },
    subtotal: 6700,
    commission: 0,
    deliveryFee: 395,
    total: 7095,
    stripePaymentIntentId: "pi_demo_cakes_001",
    createdAt: new Date("2024-04-10"),
    updatedAt: new Date("2024-04-11"),
  },
];
